name: Deploy AutoTest Database on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install sqlcmd and run SQL scripts in one step
      - name: Install SQL Tools and Run Scripts
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y curl gnupg software-properties-common
          
          # Add Microsoft package repository
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl -fsSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          
          # Install mssql-tools
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          
          # Update PATH to include sqlcmd
          export PATH="$PATH:/opt/mssql-tools/bin"
          
          # Verify sqlcmd is available
          sqlcmd -?
          
          # Run the SQL scripts
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i create_db_and_table.sql -C
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i create_stored_procedure.sql -C
