name: Deploy AutoTest Database in Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner to build and run Docker

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
         docker build -t autotestsql:latest ./docker

      # Run the Docker container to execute SQL scripts
      - name: Run SQL Scripts in Docker
        run: |
          docker run --rm autotestsql:latest /bin/bash -c "sqlcmd -S '${{ secrets.SQL_SERVER_HOST }}' -U '${{ secrets.SQL_USER }}' -P '${{ secrets.SQL_PASSWORD }}' -i /app/create_db_and_table.sql -C"
          docker run --rm autotestsql:latest /bin/bash -c "sqlcmd -S '${{ secrets.SQL_SERVER_HOST }}' -U '${{ secrets.SQL_USER }}' -P '${{ secrets.SQL_PASSWORD }}' -i /app/create_stored_procedure.sql -C"
