name: Automate SQL Database
on: push

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQL Server CLI
        run: sudo apt-get install mssql-tools unixodbc-dev -y

      - name: Connect to SQL Server & Run Procedure
        run: |
          sqlcmd -S "ZROK_PUBLIC_URL" -U "Auto_user" -P "YourPassword" -Q "EXEC CreateDatabaseAndTable"
