name: Project SQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install sqlcmd and dependencies
      - name: Install CMD
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg software-properties-common
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl -fsSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

      # Run SQL scripts against the exposed SQL Server
      - name: Run SQL Scripts
        run: |
          # Ensure PATH includes sqlcmd
          export PATH="$PATH:/opt/mssql-tools/bin"
          # Verify sqlcmd is available
          sqlcmd -?
          # Execute the scripts
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i create_db_and_table.sql -C
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i create_stored_procedure.sql -C
