name: Deploy AutoTest Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner since sqlcmd is pre-installed

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run SQL scripts against the exposed SQL Server
      - name: Deploy Database and Table
        run: |
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i "create_db_and_table.sql" -C
          sqlcmd -S "${{ secrets.SQL_SERVER_HOST }}" -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i "create_stored_procedure.sql" -C
        shell: cmd
