name: Notify Teams on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Microsoft Teams
        run: |
          ACTION_TYPE="${{ github.event.action }}"
          if [ "$ACTION_TYPE" = "opened" ]; then
            ACTION_TEXT="Pull Request Opened "
          elif [ "$ACTION_TYPE" = "reopened" ]; then
            ACTION_TEXT="Pull Request Reopened "
          else
            ACTION_TEXT="Pull Request Update"
          fi

          curl -X POST -H "Content-Type: application/json" -d "{
            \"text\": \"**$ACTION_TEXT**\n\n
            **Repository:** ${{ github.repository }}\n
            **PR Title:** ${{ github.event.pull_request.title }}\n
            **Opened by:** ${{ github.event.pull_request.user.login }}\n
            [ View PR ](${{ github.event.pull_request.html_url }})\"
          }" \"${{ secrets.TEAMS_WEBHOOK_URL }}\"
