name: Notify Teams on Merge

on:
  pull_request:
    types:
      - opened   # Runs when a PR is closed (merged or not)
      - reopened  

jobs:
  notify-teams:
    
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Microsoft Teams
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": " **Pull Request !** \n\n
            **Repository:** ${{ github.repository }}\n
            **PR Title:** ${{ github.event.pull_request.title }}\n
            **Actor :** ${{ github.actor }}\n
            [ View PR](${{ github.event.pull_request.html_url }})"
          }' "${{ secrets.TEAMS_WEBHOOK_URL }}"
